version: '3.8'

services:
  postgresql:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: mypguser
      POSTGRES_PASSWORD: mypgpass
      POSTGRES_DB: dgs-example-db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
