insert into companies (company_name, domain, year_founded) values ('ibm', 'ibm.com', 1911);
insert into companies (company_name, domain, year_founded) values ('tata consultancy services', 'tcs.com', 1968);
insert into companies (company_name, domain, year_founded) values ('accenture', 'accenture.com', 1989);
insert into companies (company_name, domain, year_founded) values ('us army', 'goarmy.com', 1800);
insert into companies (company_name, domain, year_founded) values ('ey', 'ey.com', 1989);
insert into companies (company_name, domain, year_founded) values ('hewlett-packard', 'hpe.com', 1939);
insert into companies (company_name, domain, year_founded) values ('cognizant technology solutions', 'cognizant.com', 1994);
insert into companies (company_name, domain, year_founded) values ('walmart', 'walmartcareers.com', 1962);
insert into companies (company_name, domain, year_founded) values ('microsoft', 'microsoft.com', 1975);
insert into companies (company_name, domain, year_founded) values ('united states air force', 'airforce.com', 1947);
insert into companies (company_name, domain, year_founded) values ('pwc', 'pwc.com', 1998);
insert into companies (company_name, domain) values ('wells fargo', 'wellsfargo.com');
insert into companies (company_name, domain, year_founded) values ('infosys', 'infosys.com', 1981);
insert into companies (company_name, domain, year_founded) values ('deloitte', 'deloitte.com', 1900);
insert into companies (company_name, domain, year_founded) values ('citi', 'citigroup.com', 1812);
insert into companies (company_name, domain, year_founded) values ('bank of america', 'bankofamerica.com', 1968);
insert into companies (company_name, domain, year_founded) values ('jpmorgan chase & co.', 'jpmorganchase.com', 1823);
insert into companies (company_name, domain) values ('us navy', 'navy.com');
insert into companies (company_name, domain, year_founded) values ('amazon', 'amazon.com', 1994);
insert into companies (company_name, domain, year_founded) values ('apple', 'apple.com', 1976);
insert into companies (company_name, domain, year_founded) values ('siemens', 'siemens.com', 1847);
insert into companies (company_name, domain, year_founded) values ('oracle', 'oracle.com', 1977);
insert into companies (company_name, domain, year_founded) values ('nokia', 'nokia.com', 1865);
insert into companies (company_name, domain) values ('education nationale', 'education.gouv.fr');
insert into companies (company_name, domain, year_founded) values ('capgemini', 'capgemini.com', 1967);
insert into companies (company_name, domain, year_founded) values ('wipro technologies', 'wipro.com', 1945);
insert into companies (company_name, domain, year_founded) values ('hsbc', 'hsbc.com', 1865);
insert into companies (company_name, domain, year_founded) values ('google', 'google.com', 1998);
insert into companies (company_name, domain) values ('united states postal service', 'usps.com');